#!/bin/sh
cd src
valac --pkg gconf-2.0 -o setup_spotify setup_spotify.vala
./setup_spotify
valac --vapidir=../. --pkg glib-2.0 --pkg gio-2.0 --pkg gmodule-2.0 --pkg gstreamer-0.10 --pkg dbus-glib-1 --pkg gconf-2.0 --pkg sqlite3 --pkg spotify --pkg taglib_c -X -I/usr/include/taglib -X -ltag_c -o ../server  \
               track.vala apex-speaker.vala fake-speaker.vala device-speaker.vala radio-source.vala spotify-source.vala source-interface.vala amplifier-interface.vala remote-speaker-interface.vala speaker-interface.vala file-source.vala server.vala Collection.vala single-source-interface.vala -X -lspotify
